FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
  • Installing frozenlist (1.3.1): Failed
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python

  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
  FileNotFoundError
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python

  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/frozenlist/py.typed'
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python

  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python3-3.10.16/lib/python3.10/pathlib.py:1119 in open
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1115│         the built-in open() function does.
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1116│         """
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1117│         if "b" not in mode:
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1118│             encoding = io.text_encoding(encoding)
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
    → 1119│         return self._accessor.open(self, mode, buffering, encoding, errors,
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1120│                                    newline)
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1121│ 
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1122│     def read_bytes(self):
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python
      1123│         """
  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python

  • Installing idna (3.4): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/idna/__init__.py'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python3-3.10.16/lib/python3.10/pathlib.py:1119 in open
      1115│         the built-in open() function does.
      1116│         """
      1117│         if "b" not in mode:
      1118│             encoding = io.text_encoding(encoding)
    → 1119│         return self._accessor.open(self, mode, buffering, encoding, errors,
      1120│                                    newline)
      1121│ 
      1122│     def read_bytes(self):
      1123│         """

  • Installing markupsafe (2.1.1): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/MarkupSafe-2.1.1.dist-info/METADATA'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python3-3.10.16/lib/python3.10/pathlib.py:1119 in open
      1115│         the built-in open() function does.
      1116│         """
      1117│         if "b" not in mode:
      1118│             encoding = io.text_encoding(encoding)
    → 1119│         return self._accessor.open(self, mode, buffering, encoding, errors,
      1120│                                    newline)
      1121│ 
      1122│     def read_bytes(self):
      1123│         """

  • Installing multidict (6.0.2): Failed

  FileNotFoundError

  [Errno 2] No such file or directory: '/home/runner/workspace/.pythonlibs/lib/python3.10/site-packages/multidict-6.0.2.dist-info/WHEEL'

  at /nix/store/qlb1pg370bb647nj4dhc81y2jszvciz7-python3-3.10.16/lib/python3.10/pathlib.py:1119 in open
      1115│         the built-in open() function does.
      1116│         """
      1117│         if "b" not in mode:
      1118│             encoding = io.text_encoding(encoding)
    → 1119│         return self._accessor.open(self, mode, buffering, encoding, errors,
      1120│                                    newline)
      1121│ 
      1122│     def read_bytes(self):
      1123│      